name: Meme On Commit

on:
  push:
    branches:
      - main  

jobs:
  meme-on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Meme
        run: |
          echo "This is a meme" > false.jpeg

      - name: Add and Commit Meme
        run: |
          git config --global user.name 'Meme Bot'
          git config --global user.email 'memebot@example.com'
          git add false.jpeg
          git commit -m "Add meme on commit" || true
          git push
   
